[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'chrisbra/SudoEdit.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'sjl/gundo.vim'

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = '''
let g:ref_cache_dir = $MYVIMDIR . '/misc/vim_ref_cache'
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/restart.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'PProvost/vim-ps1'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
if has('unix')
	!make -f make_unix.mak
endif
'''
hook_add = '''
if has('kaoriya')
	let g:vimproc#dll_path = '$VIM\plugins\vimproc\lib\vimproc_win64.dll'
endif
'''

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = 'Shougo/vimproc'
hook_add = '''
let g:quickrun_config = {}
let g:quickrun_config.cpp = {
    \ 'command': 'clang',
    \ 'cmdopt': '-std=c++14'
\ }
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'
hook_add = '''
let g:javascript_plugin_flow = 1
'''

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
depends = 'pangloss/vim-javascript'
hook_add = '''
let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
depends  = 'unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
depends  = 'unite.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'
